(deftemplate carro
	(slot luz (type SYMBOL))
	(slot bateria (type SYMBOL))
        (slot tipobateria (type SYMBOL))
        (slot contbateria (type SYMBOL))
	(slot alternador (type SYMBOL))
	(slot correia (type SYMBOL))
	(slot componente (type SYMBOL))
	(slot consertaalternador (type SYMBOL))
	(slot vela-bobina (type SYMBOL))
	(slot motorarranque (type SYMBOL))
	(slot tipomotor (type SYMBOL))
	(slot bomba (type SYMBOL))
	(slot modulo (type SYMBOL))
)
