(deftemplate carro
	(slot luz (type SYMBOL))
	(slot bateria (type SYMBOL))
        (slot tipobateria (type SYMBOL))
        (slot contbateria (type SYMBOL))
	(slot alternador (type SYMBOL))
	(slot vela-bobina (type SYMBOL))
	(slot agua-reservatorio (type SYMBOL))
	(slot mangueira-agua (type SYMBOL))
)
